version: 2
jobs:
  build:
    docker:
    - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: 'true'
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "project.clj" }}
        - v1-dependencies-
    - run: lein deps
    - run:
        name: Install 'phantomjs'
        command: |
          sudo curl --output /tmp/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
          sudo chmod ugo+x /tmp/phantomjs
          sudo ln -sf /tmp/phantomjs /usr/local/bin/phantomjs
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "project.clj" }}
    - run: lein test-all
